/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteionomes;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    File file = null;

    /**
     * Creates new form TelaPrincipal
     *
     * @throws java.io.FileNotFoundException
     */
    public TelaPrincipal() throws FileNotFoundException, IOException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //firebase
        FileInputStream serviceAccount;

        serviceAccount = new FileInputStream("./src/sorteio-c520b-firebase-adminsdk-aalga-3a1650b039.json");
        FirebaseOptions options = new FirebaseOptions.Builder()
                .setCredentials(GoogleCredentials.fromStream(serviceAccount))
                .setDatabaseUrl("https://sorteio-c520b.firebaseio.com")
                .build();
        if (FirebaseApp.getApps().isEmpty()) {
            FirebaseApp.initializeApp(options);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jPanelParent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAbrirArq = new javax.swing.JButton();
        txtArqNome = new javax.swing.JLabel();
        btnSortear = new javax.swing.JButton();
        txtGanhador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtNomeSorteio = new javax.swing.JTextField();

        jFileChooser.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio de Nomes");
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(102, 102, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 190));

        jPanelParent.setBackground(new java.awt.Color(153, 153, 255));
        jPanelParent.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("Escolha um arquivo:");
        jLabel1.setToolTipText("");

        btnAbrirArq.setText("Arquivo");
        btnAbrirArq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAbrirArqMouseReleased(evt);
            }
        });

        txtArqNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtArqNome.setText("<<Nome do Arquivo>>");

        btnSortear.setText("Sortear");
        btnSortear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSortearMouseReleased(evt);
            }
        });

        txtGanhador.setFont(new java.awt.Font("DejaVu Serif", 3, 36)); // NOI18N
        txtGanhador.setForeground(new java.awt.Color(0, 204, 0));
        txtGanhador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGanhador.setText("<<ganhador>>");
        txtGanhador.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nome do Sorteio:");

        edtNomeSorteio.setColumns(200);
        edtNomeSorteio.setToolTipText("Nome sorteio");

        javax.swing.GroupLayout jPanelParentLayout = new javax.swing.GroupLayout(jPanelParent);
        jPanelParent.setLayout(jPanelParentLayout);
        jPanelParentLayout.setHorizontalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGanhador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArqNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAbrirArq)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(edtNomeSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(btnSortear))
                        .addGap(224, 224, 224))))
        );
        jPanelParentLayout.setVerticalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(btnAbrirArq)
                .addGap(18, 18, 18)
                .addComponent(txtArqNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtNomeSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(btnSortear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGanhador)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArqMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirArqMouseReleased
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(jPanelParent);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            txtArqNome.setText(file.getAbsolutePath());

        }

    }//GEN-LAST:event_btnAbrirArqMouseReleased

    private void btnSortearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortearMouseReleased

        if (file != null) {
            if (edtNomeSorteio.getText().isEmpty()) {
                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "Favor inserir um nome para o sorteio.");
            } else if ((edtNomeSorteio.getText().contains("."))
                    || (edtNomeSorteio.getText().contains("!"))
                    || (edtNomeSorteio.getText().contains("@"))
                    || (edtNomeSorteio.getText().contains("#"))
                    || (edtNomeSorteio.getText().contains("$"))
                    || (edtNomeSorteio.getText().contains("%"))
                    || (edtNomeSorteio.getText().contains("%"))
                    || (edtNomeSorteio.getText().contains("&"))
                    || (edtNomeSorteio.getText().contains("*"))
                    || (edtNomeSorteio.getText().contains(","))) {

                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                        "Favor não usar símbolos.");

            } else {
                //decompondo o csv em linhas 
                List<String> contents = new ArrayList<>();
                try {
                    BufferedReader br = new BufferedReader(new FileReader(file));
                    String line = "";
                    while ((line = br.readLine()) != null) {
                        contents.add(line);
                    }
                } catch (FileNotFoundException e) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, e);
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                //pegando um número randomico
                Random rand = new Random();
                int upperbound = contents.size();
                int intRandom = rand.nextInt(upperbound);
                //pegando a linha do arquivo de acordo com o número sorteado
                for (int j = 0; contents.size() > 0; j++) {
                    if (j == intRandom) {
                        txtGanhador.setText(contents.get(j));
                        break;
                    }
                }
                String nome = edtNomeSorteio.getText();
                LocalDateTime now = java.time.LocalDateTime.now();
                String data = now.toString().replace("-", "").substring(0, 11);
                String id = nome + data;
                String ganhador = txtGanhador.getText();

                FireBaseResult objResult = new FireBaseResult();
                objResult.setId(id);
                objResult.setNome(edtNomeSorteio.getText());
                //formato de data mais amigável
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                LocalDateTime agora = LocalDateTime.now();
                System.out.println();
                //segue o jogo
                objResult.setData(dtf.format(agora));
                objResult.setGanhador(ganhador);

                final FirebaseDatabase database = FirebaseDatabase.getInstance();
                DatabaseReference ref = database.getReference("sorteio");

                DatabaseReference usersRef = ref.child(id);
                usersRef.setValueAsync(objResult);

                edtNomeSorteio.setText("");
            }
        } else {
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
                    "Arquivo CSV inválido!");
        }

    }//GEN-LAST:event_btnSortearMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaPrincipal().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArq;
    private javax.swing.JButton btnSortear;
    private javax.swing.JTextField edtNomeSorteio;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanelParent;
    private javax.swing.JLabel txtArqNome;
    private javax.swing.JLabel txtGanhador;
    // End of variables declaration//GEN-END:variables
}
